// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD51xVbZtQ63txQQUEq0E2kmI-UOBOywh4',
    appId: '1:791689323108:web:3185c125cf31581780f571',
    messagingSenderId: '791689323108',
    projectId: 'breedelite-3286a',
    authDomain: 'breedelite-3286a.firebaseapp.com',
    storageBucket: 'breedelite-3286a.appspot.com',
    measurementId: 'G-T16RHGT9MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp03CWruRqHk015UPpOgrJVh5YnCFTIiQ',
    appId: '1:791689323108:android:ba5869260a77934680f571',
    messagingSenderId: '791689323108',
    projectId: 'breedelite-3286a',
    storageBucket: 'breedelite-3286a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFhXFTkOvB2iZc0S6EfEUosiuFL-8i5VU',
    appId: '1:791689323108:ios:87a6e9af2207524a80f571',
    messagingSenderId: '791689323108',
    projectId: 'breedelite-3286a',
    storageBucket: 'breedelite-3286a.appspot.com',
    iosBundleId: 'au.com.breedelite.breedelite',
  );
}
